function AddTextEntry(key, value)
	Citizen.InvokeNative(GetHashKey("ADD_TEXT_ENTRY"), key, value)
end

Citizen.CreateThread(function()
    AddTextEntry("brabus700", "Brabus 700 G63 AMG 6x6")
    AddTextEntry("lykan", "Lykan HyperSport")
    AddTextEntry("RAPTOR150", "Ford Raptor Scorpio")
    AddTextEntry("bolide", "Bugatti Bolide")
    AddTextEntry("lamtmc", "Lamborghini Terzo Millennio")
    AddTextEntry("velociraptor", "Hennessey Velociraptor 6x6")
    AddTextEntry("wildtrak", "Ford Bronco Wildtrak")
    AddTextEntry("18Velar", "Range Rover Velar")
    AddTextEntry("firebird", "Pontiac Firebird")
    AddTextEntry("moss", "Mercedes-Benz SLR Stirling Moss")
    AddTextEntry("h6", "Hummer H6")
    AddTextEntry("bmwm8", "BMW M8")
    AddTextEntry("BUGATTI", "Bugatti Veyron")
    AddTextEntry("CHIRON17", "Bugatti Chiron")
    AddTextEntry("panamera18", "Porsche Panamera Turbo")
    AddTextEntry("rmodlp770", "Lamborghini Centenario")
    AddTextEntry("serv electr", "Scooter")
    AddTextEntry("x6m", "BMW X6")
    AddTextEntry("f8t", "Ferrari F8")
    AddTextEntry("huracanlb", "Lamborghini Huracan LP-610")
    AddTextEntry("laferrari17", "Ferrari LaFerrari Aperta")
    AddTextEntry("teslax", "Tesla Model X")
    AddTextEntry("wraith", "Rolls-Royce Wraith")
    AddTextEntry("S65 AMG", "Mercedes S65 AMG")
    AddTextEntry("rmodx6", "BMW X6M")
    AddTextEntry("forgiecat", "Forgiato Hellcat Charger")
    AddTextEntry("610lb", "Lamborghini Huracan")

    -- NEW
    AddTextEntry("73venom", "1973 Chevrolet Caprice Venom Donk")
    AddTextEntry("biome", "Mercedes-Benz Biome Concept")
    AddTextEntry("mvisiongt", "Mercedes-Benz AMG Vision GT")
    AddTextEntry("ar8lb", "Audi R8v10 Liberty Walk")
    AddTextEntry("sprinter211", "Mercedes Sprinter 211 CDI")
    AddTextEntry("hog", "AMG Transport Dynamics M12S Warthog CST")
    AddTextEntry("ft1gr3", "Toyota FT-1 Concept")
    AddTextEntry("gtrlb2", "2019 Nissan GT-R Liberty walk LB Performance")
    AddTextEntry("bugvr", "Bugatti Veyron‘Grand Sport L'Or Blanc’")
    AddTextEntry("sxr", "BMW S1000XR 2019")
    AddTextEntry("aeroxdrag", "Yamaha Aerox 155")
    AddTextEntry("v4sf", "2021 Ducati V4S StreetFighter")
    
    
end)
